package com.taidii.staffdevelopment.hq.entity;

import java.math.BigDecimal;
import java.util.Date;

public class EnrichmentStudentklassschedule {
    private Integer id;

    private Integer type;

    private Integer studentId;

    private Integer klassscheduleId;

    private Integer numberOfClass;

    private Boolean isReschedule;

    private BigDecimal totalAmount;

    private String remarks;

    private Boolean autoCreateClass;

    private Integer childId;

    private Date enrollDate;

    private Boolean isTryClass;

    private Boolean isFreeClass;

    private Integer invoiceId;

    private Date endDate;

    private Integer invoiceItemId;

    private Integer autoGenerated;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStudentId() {
        return studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public Integer getKlassscheduleId() {
        return klassscheduleId;
    }

    public void setKlassscheduleId(Integer klassscheduleId) {
        this.klassscheduleId = klassscheduleId;
    }

    public Integer getNumberOfClass() {
        return numberOfClass;
    }

    public void setNumberOfClass(Integer numberOfClass) {
        this.numberOfClass = numberOfClass;
    }

    public Boolean getIsReschedule() {
        return isReschedule;
    }

    public void setIsReschedule(Boolean isReschedule) {
        this.isReschedule = isReschedule;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    public Boolean getAutoCreateClass() {
        return autoCreateClass;
    }

    public void setAutoCreateClass(Boolean autoCreateClass) {
        this.autoCreateClass = autoCreateClass;
    }

    public Integer getChildId() {
        return childId;
    }

    public void setChildId(Integer childId) {
        this.childId = childId;
    }

    public Date getEnrollDate() {
        return enrollDate;
    }

    public void setEnrollDate(Date enrollDate) {
        this.enrollDate = enrollDate;
    }

    public Boolean getIsTryClass() {
        return isTryClass;
    }

    public void setIsTryClass(Boolean isTryClass) {
        this.isTryClass = isTryClass;
    }

    public Boolean getIsFreeClass() {
        return isFreeClass;
    }

    public void setIsFreeClass(Boolean isFreeClass) {
        this.isFreeClass = isFreeClass;
    }

    public Integer getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Integer getInvoiceItemId() {
        return invoiceItemId;
    }

    public void setInvoiceItemId(Integer invoiceItemId) {
        this.invoiceItemId = invoiceItemId;
    }

    public Integer getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Integer autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
}