package com.taidii.staffdevelopment.hq.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinanceInvoice {
    private Integer id;

    private String invoiceNo;

    private Integer studentId;

    private Date dateCreated;

    private Date dateDue;

    private Date dateGenerated;

    private Integer status;

    private String voidRemarks;

    private String remarks;

    private String salesPerson;

    private Integer autoGenerated;

    private BigDecimal balance;

    private Integer centerId;

    private BigDecimal originBalance;

    private Integer type;

    private String soldTo;

    private String soldToEmail;

    private Integer presetPaymentMethod;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getInvoiceNo() {
        return invoiceNo;
    }

    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    public Integer getStudentId() {
        return studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getDateDue() {
        return dateDue;
    }

    public void setDateDue(Date dateDue) {
        this.dateDue = dateDue;
    }

    public Date getDateGenerated() {
        return dateGenerated;
    }

    public void setDateGenerated(Date dateGenerated) {
        this.dateGenerated = dateGenerated;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getVoidRemarks() {
        return voidRemarks;
    }

    public void setVoidRemarks(String voidRemarks) {
        this.voidRemarks = voidRemarks == null ? null : voidRemarks.trim();
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    public String getSalesPerson() {
        return salesPerson;
    }

    public void setSalesPerson(String salesPerson) {
        this.salesPerson = salesPerson == null ? null : salesPerson.trim();
    }

    public Integer getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Integer autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Integer getCenterId() {
        return centerId;
    }

    public void setCenterId(Integer centerId) {
        this.centerId = centerId;
    }

    public BigDecimal getOriginBalance() {
        return originBalance;
    }

    public void setOriginBalance(BigDecimal originBalance) {
        this.originBalance = originBalance;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getSoldTo() {
        return soldTo;
    }

    public void setSoldTo(String soldTo) {
        this.soldTo = soldTo == null ? null : soldTo.trim();
    }

    public String getSoldToEmail() {
        return soldToEmail;
    }

    public void setSoldToEmail(String soldToEmail) {
        this.soldToEmail = soldToEmail == null ? null : soldToEmail.trim();
    }

    public Integer getPresetPaymentMethod() {
        return presetPaymentMethod;
    }

    public void setPresetPaymentMethod(Integer presetPaymentMethod) {
        this.presetPaymentMethod = presetPaymentMethod;
    }
}